version: '3.8'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  dbmigrator:
    build:
      context: .
      dockerfile: ./Tools/DbMigrator/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=localhost;Port=5432;User ID=postgres;Password=postgres;Database=postgres
    depends_on:
      - postgres
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: ./ChatServer/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=localhost;Port=5432;User ID=postgres;Password=postgres;Database=chat
      - ASPNETCORE_URLS=http://+:80   
    depends_on:
      - dbmigrator
    ports:
      - "5090:80"
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: ./Clients/Dockerfile
    depends_on:
      - server
    ports:
      - "3000:80"
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
